X(AIRSteam_Init)
X(AIRSteam_RunCallbacks)
X(AIRSteam_GetUserID)
X(AIRSteam_GetAppID)
X(AIRSteam_GetPersonaName)
X(AIRSteam_UseCrashHandler)

// stats / achievements
X(AIRSteam_RequestStats)
X(AIRSteam_SetAchievement)
X(AIRSteam_ClearAchievement)
X(AIRSteam_IsAchievement)
X(AIRSteam_GetStatInt)
X(AIRSteam_GetStatFloat)
X(AIRSteam_SetStatInt)
X(AIRSteam_SetStatFloat)
X(AIRSteam_StoreStats)
X(AIRSteam_ResetAllStats)

// remote storage
X(AIRSteam_GetFileCount)
X(AIRSteam_GetFileSize)
X(AIRSteam_FileExists)
X(AIRSteam_FileWrite)
X(AIRSteam_FileRead)
X(AIRSteam_FileDelete)
X(AIRSteam_FileShare)
X(AIRSteam_FileShareResult)
X(AIRSteam_IsCloudEnabledForApp)
X(AIRSteam_SetCloudEnabledForApp)
X(AIRSteam_GetQuota)

// ugc / workshop
X(AIRSteam_UGCDownload)
X(AIRSteam_UGCRead)
X(AIRSteam_GetUGCDownloadProgress)
X(AIRSteam_GetUGCDownloadResult)
X(AIRSteam_PublishWorkshopFile)
X(AIRSteam_PublishWorkshopFileResult)
X(AIRSteam_DeletePublishedFile)
X(AIRSteam_GetPublishedFileDetails)
X(AIRSteam_GetPublishedFileDetailsResult)
X(AIRSteam_EnumerateUserPublishedFiles)
X(AIRSteam_EnumerateUserPublishedFilesResult)
X(AIRSteam_EnumeratePublishedWorkshopFiles)
X(AIRSteam_EnumeratePublishedWorkshopFilesResult)
X(AIRSteam_EnumerateUserSubscribedFiles)
X(AIRSteam_EnumerateUserSubscribedFilesResult)
X(AIRSteam_EnumerateUserSharedWorkshopFiles)
X(AIRSteam_EnumerateUserSharedWorkshopFilesResult)
X(AIRSteam_EnumeratePublishedFilesByUserAction)
X(AIRSteam_EnumeratePublishedFilesByUserActionResult)
X(AIRSteam_SubscribePublishedFile)
X(AIRSteam_UnsubscribePublishedFile)
X(AIRSteam_CreatePublishedFileUpdateRequest)
X(AIRSteam_UpdatePublishedFileFile)
X(AIRSteam_UpdatePublishedFilePreviewFile)
X(AIRSteam_UpdatePublishedFileTitle)
X(AIRSteam_UpdatePublishedFileDescription)
X(AIRSteam_UpdatePublishedFileSetChangeDescription)
X(AIRSteam_UpdatePublishedFileVisibility)
X(AIRSteam_UpdatePublishedFileTags)
X(AIRSteam_CommitPublishedFileUpdate)
X(AIRSteam_GetPublishedItemVoteDetails)
X(AIRSteam_GetPublishedItemVoteDetailsResult)
X(AIRSteam_UpdateUserPublishedItemVote)
X(AIRSteam_SetUserPublishedFileAction)

// overlay
X(AIRSteam_ActivateGameOverlay)
X(AIRSteam_ActivateGameOverlayToUser)
X(AIRSteam_ActivateGameOverlayToWebPage)
X(AIRSteam_ActivateGameOverlayToStore)
X(AIRSteam_ActivateGameOverlayInviteDialog)
X(AIRSteam_IsOverlayEnabled)

// DLC / subscription
X(AIRSteam_IsSubscribedApp)
X(AIRSteam_IsDLCInstalled)
X(AIRSteam_GetDLCCount)
X(AIRSteam_InstallDLC)
X(AIRSteam_UninstallDLC)
X(AIRSteam_DLCInstalledResult)
